### ISSUE TITLE
How to get/read msg text?

### ISSUE THREAD

**Issue by smitagodbole** [pywinauto/pywinauto#496]
Hi,
I am trying to get/read msg text in pywinauto script and getting problem.

`print_control_identifiers()` gives me the following control:
```python
Image - ''    (L566, T382, R614, B478)
   |    |    | ['3', 'Image', 'Image0', 'Image1']
   |    |    | child_window(auto_id="MessageIcon", control_type="Image")
   |    |    |
   |    |    | Static - ''    (L659, T374, R1049, B401)
   |    |    | ['4', 'Static4']
   |    |    | child_window(auto_id="HeaderConfigurable", control_type="Text")
   |    |    |    |
   |    |    |    | Static - 'Validation'    (L659, T374, R1049, B401)
   |    |    |    | ['Static5', 'Validation', 'ValidationStatic', 'Validation0', 'Validation1', 'ValidationStatic0', 'ValidationStatic1']
   |    |    |    | child_window(title="Validation", auto_id="PART_Label", control_type="Text")
   |    |    |    |    |
   |    |    |    |    | Static - 'Validation'    (L659, T374, R754, B401)
   |    |    |    |    | ['Static6', 'Validation2', 'ValidationStatic2']
   |    |    |    |    | child_window(title="Validation", control_type="Text")
```

----------------------------------------------------------------------------------------------------
I tried the following:
```python
sMsg=cMyApp1.dialog.child_window(class_name="TextBlock",auto_id="PART_TextBlock")
s=sMsg.legacy_properties()['Name']
print(s)
```

but it's not working.

------------------------------------------------------------------------
Inspect .exe shows the following...
```yaml
How found:	Selected from tree...
Name:	"The ID Code value is duplicate."
ControlType:	UIA_TextControlTypeId (0xC364)
LocalizedControlType:	"text"
BoundingRectangle:	{l:669 t:447 r:1029 b:463}
IsEnabled:	true
IsOffscreen:	false
IsKeyboardFocusable:	false
HasKeyboardFocus:	false
AcceleratorKey:	""
AccessKey:	""
ProcessId:	3704
RuntimeId:	[7.E78.2011D81]
AutomationId:	"PART_TextBlock"
FrameworkId:	"WPF"
ClassName:	"TextBlock"
IsControlElement:	false
IsContentElement:	false
ProviderDescription:	"[pid:3704,providerId:0x0 Main(parent link):Unidentified Provider (managed:MS.Internal.Automation.ElementProxy, PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)]"
IsPassword:	false
ItemStatus:	""
ItemType:	""
IsRequiredForForm:	false
HelpText:	""
ClickablePoint:	{x:849 y:455}
Orientation:	0
LegacyIAccessible.ChildId:	0
LegacyIAccessible.DefaultAction:	""
LegacyIAccessible.Description:	""
LegacyIAccessible.Help:	""
LegacyIAccessible.KeyboardShortcut:	""
LegacyIAccessible.Name:	"The ID Code value is duplicate."
LegacyIAccessible.Role:	text (0x29)
LegacyIAccessible.State:	normal (0x0)
LegacyIAccessible.Value:	""
Selection2.FirstSelectedItem:	[Not supported]
Selection2.LastSelectedItem:	[Not supported]
Selection2.CurrentSelectedItem:	[Not supported]
Selection2.ItemCount:	[Not supported]
IsAnnotationPatternAvailable:	false
IsDragPatternAvailable:	false
IsDockPatternAvailable:	false
IsDropTargetPatternAvailable:	false
IsExpandCollapsePatternAvailable:	false
IsGridItemPatternAvailable:	false
IsGridPatternAvailable:	false
IsInvokePatternAvailable:	false
IsItemContainerPatternAvailable:	false
IsLegacyIAccessiblePatternAvailable:	true
IsMultipleViewPatternAvailable:	false
IsObjectModelPatternAvailable:	false
IsRangeValuePatternAvailable:	false
IsScrollItemPatternAvailable:	false
IsScrollPatternAvailable:	false
IsSelectionItemPatternAvailable:	false
IsSelectionPatternAvailable:	false
IsSpreadsheetItemPatternAvailable:	false
IsSpreadsheetPatternAvailable:	false
IsStylesPatternAvailable:	false
IsSynchronizedInputPatternAvailable:	true
IsTableItemPatternAvailable:	false
IsTablePatternAvailable:	false
IsTextChildPatternAvailable:	false
IsTextEditPatternAvailable:	false
IsTextPatternAvailable:	false
IsTextPattern2Available:	false
IsTogglePatternAvailable:	false
IsTransformPatternAvailable:	false
IsTransform2PatternAvailable:	false
IsValuePatternAvailable:	false
IsVirtualizedItemPatternAvailable:	false
IsWindowPatternAvailable:	false
IsCustomNavigationPatternAvailable:	false
IsSelectionPattern2Available:	[Not supported]
FirstChild:	[null]
LastChild:	[null]
Next:	[null]
Previous:	"" text
Other Props:	Object has no additional properties
Children:	Container has no children

```
Thanks in advance.
Smita
